version: '3.1'

services:

  db1:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      PGUSER: user
      POSTGRES_PASSWORD: pw
    ports:
      - "5431:5432"

  db2:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      PGUSER: user
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8088:8080"
